### ISSUE TITLE
Changed voucher exchange to true and nothing happens

### ISSUE THREAD

**Issue by SyrBetty** [Prawellp/FFXIV-SND#11]
When I changed the voucher exchange to true under the settings section it doesn't teleport to exchange. It just keeps farming.

**Comment by Prawellp** [comment]
It should teleport after u have over 1.4K gems and finish a fate

**Comment by SyrBetty** [comment]
I had 1500 and the fate was done.

**Comment by Prawellp** [comment]
yes.

**Comment by SyrBetty** [comment]
thanks!

**Comment by SyrBetty** [comment]
I'll let you know if I can't fix it.
