### ISSUE TITLE
[REQUEST] Add option to purchase Material Items

### ISSUE THREAD

**Issue by Carbodium** [Prawellp/FFXIV-SND#6]
Would it be possible to add in an option to purchase DT Material Items as well as Vouchers based on settings? Something like below.

--Teleport and Exchange
teleport = "Ok'hanu"     --Enter the name of the Teleporter where youu farm Fates so it teleport back to the area and keeps farming
ChangeInstance = true      --Change Instance when there is no Fate (only works on DT fates)
Exchange = true           --Enable Auto Exchanging of Bicolor Gemstones (must have all zones at max rank)
Materials = true          --Purchase materials from the Material List
MatsFirst = false          --Purchase materials to [ExchangeLimit] and then purchase Vouchers
DTVouchers = false         --Purchase DT Turali Bicolor Gemstone Vouchers
EWVouchers = false         --Purchase EW Bicolor Gemstone Vouchers

--Material List
ExchangeLimit = 999 --Max compatible is 999 items
AlpacaFillet = true
SwampmonkThigh = false
NopalitdenerTuna = false
RroneekChuck = false
MegamagueyPineapple = false
BranchbearerFruit = false
RroneekFleece = false
SilverLoboHide = false
HammerheadCrocodileSkin = false
BraaxHide = false
GomphotheriumSkin = false
GargantuaHide = false
TyaityaWingblade = false
PoisonFrogSecreations = false
AxeBeakWing = false
LesserApollyonShell = false
TumbleclawWeeds = false

**Comment by Prawellp** [comment]
would be alot to add but its possible to change it to the desired item really easy 

yield("/callback ShopExchangeCurrency false 0 5 13")
this should be at the bottom where the Voucher exchange is and you can just change the 5 to the item you want there is also a little text next to it explaining it.
